version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    command: --innodb_use_native_aio=0
    ports:
      - '3306:3306'
    volumes:
      - ./data_ms:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  node-app:
    build: ./app
    image: node-app:1.0
    ports:
      - '9999:9999'
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data_ps:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST_AUTH_METHOD=trust